name: simple_alarm
description: "简单闹钟应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  alarm: ^5.1.4
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2
  path_provider: ^2.0.11
  intl: ^0.19.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  jpush_flutter: ^3.3.6
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0-dev.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env